### PR TITLE
Update Zig and Janet

### PR DESCRIPTION
**Pull request by iacore**

### CODE REVIEW

**Comment by greenfork** [comment]
Thanks! Currently I have a failing test running `zig build test`, do you think you could fix that?

```
run test: error: error: expected failure, part of the test
  in zig/dec
  in _thunk [main] on line 1, column 1
```

There's also a readme and examples that need updating, feel free to update them too if you want.

**Comment by greenfork** [comment]
Oh wait, I'm sorry. This is an expected error that I put there

**Comment by greenfork** [comment]
Alright, I'll merge. Thanks! Feel free to add changes to readme and examples in a separate PR if you would like to.

**Comment by iacore** [comment]
I feel like it's easier for you to update the version numbers in readme.

**Pull request merged**
